version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=ntnu
      - MYSQL_DATABASE=KystFiske_db
    ports:
      - "3307:3306"
    volumes:
      - "./scripts/tables.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/tables.sql:/docker-entrypoint-initdb.d/2.sql"
      -  "./scripts/insert.sql:/docker-entrypoint-initdb.d/3.sql"

  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - "6868:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/KystFiske_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ntnu